### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by LemonPi** [Nima-Fazeli/hierarchical-linear-mixtures#2]
Running the example with only a single change (line 99 of LinMix.py changed to `x` from `x_train` since `x_train` isn't available at this scope) gives the following error:

```
Sequential sampling (1 chains in 1 job)
CompoundStep
>Metropolis: [tau]
>Metropolis: [delta0]
>Metropolis: [gamma]
>Metropolis: [beta0]
>Metropolis: [alpha]
100%|██████████| 30000/30000 [05:54<00:00, 84.52it/s]
Only one chain was sampled, this makes it impossible to run some convergence checks
  3%|▎         | 141/5000 [00:03<01:16, 63.16it/s]
Traceback (most recent call last):
  File "/home/zhsh/.local/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 576, in _draw_value
    return dist_tmp.random(point=point, size=size)
  File "/home/zhsh/.local/lib/python3.7/site-packages/pymc3/distributions/mixture.py", line 461, in random
    np.empty(param_shape[:-1])).shape
ValueError: shape mismatch: objects cannot be broadcast to a single shape
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/zhsh/Downloads/pycharm-2018.2.4/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/zhsh/Downloads/pycharm-2018.2.4/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/zhsh/Downloads/pycharm-2018.2.4/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/zhsh/Downloads/pycharm-2018.2.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/zhsh/catkin_ws/src/hierarchical-linear-mixtures/example.py", line 42, in <module>
    main()
  File "/home/zhsh/catkin_ws/src/hierarchical-linear-mixtures/example.py", line 26, in main
    y_pred_mean = lm.predict(pp_x)
  File "/home/zhsh/catkin_ws/src/hierarchical-linear-mixtures/hierarchical_linear_mixtures/LinMix.py", line 108, in predict
    pp_trace = pm.sample_ppc(self.trace[i], PP_SAMPLES)
  File "/home/zhsh/.local/lib/python3.7/site-packages/pymc3/sampling.py", line 1132, in sample_ppc
    return sample_posterior_predictive(*args, **kwargs)
  File "/home/zhsh/.local/lib/python3.7/site-packages/pymc3/sampling.py", line 1114, in sample_posterior_predictive
    values = draw_values(vars, point=param, size=size)
  File "/home/zhsh/.local/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 395, in draw_values
    size=size)
  File "/home/zhsh/.local/lib/python3.7/site-packages/pymc3/distributions/distribution.py", line 585, in _draw_value
    size=None))
  File "/home/zhsh/.local/lib/python3.7/site-packages/pymc3/distributions/mixture.py", line 497, in random
    size=None)  # w's shape already includes size
  File "/home/zhsh/.local/lib/python3.7/site-packages/pymc3/distributions/dist_math.py", line 338, in random_choice
    samples = np.array([np.random.choice(k, p=p_) for p_ in p])
  File "/home/zhsh/.local/lib/python3.7/site-packages/pymc3/distributions/dist_math.py", line 338, in <listcomp>
    samples = np.array([np.random.choice(k, p=p_) for p_ in p])
  File "mtrand.pyx", line 797, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1
```

The stack trace is 
```
<frame not available>
<listcomp>, dist_math.py:338
random_choice, dist_math.py:338
random, mixture.py:497
_draw_value, distribution.py:585
draw_values, distribution.py:443
sample_posterior_predictive, sampling.py:1123
sample_ppc, sampling.py:1132
predict, LinMix.py:108
main, example.py:26
<module>, example.py:42
execfile, _pydev_execfile.py:18
run, pydevd.py:1068
main, pydevd.py:1658
<module>, pydevd.py:1664
```

The lowest level in user code is predict, LinMix.py:108, which tries to do:
```
                pp_trace = pm.sample_ppc(self.trace[i], PP_SAMPLES)
```

**Comment by Nima-Fazeli** [comment]
Thanks, this may be due to a renaming in pymc3. Replacing that line with:
```
pp_trace = pm.sample_posterior_predictive(self.trace[i], PP_SAMPLES)
```

**Comment by LemonPi** [comment]
Yup, this seemed to have fixed this issue; should we support the new version of pymc3?

**Comment by Nima-Fazeli** [comment]
Great, yes we should. This should be the only discrepancy between the two for the mixtures of linear regressors.
